In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

saveメソッドで配列のデータを保存することができる

In [4]:
np.save('my_array', arr)

loadメソッドでnp配列をロードすることができる

In [5]:
loaded_arr = np.load('my_array.npy')

In [6]:
loaded_arr

array([0, 1, 2, 3, 4])

In [7]:
arr2 = np.arange(10)

In [8]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

zip形式で保存するための関数、保存した配列を呼び出す際のインデックスを付けて保存することができる

In [9]:
np.savez('zip_array.npz',x= arr2,y= loaded_arr)

In [10]:
loaded_arr2 = np.load('zip_array.npz')

In [11]:
loaded_arr2

In [14]:
loaded_arr2['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
loaded_arr2['y']

array([0, 1, 2, 3, 4])

In [16]:
arr3 = np.array([[1,2,3],[4,5,6]])

In [17]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.savetxt('my_arraytxt.txt',arr3,delimiter=',')

! をつけるとシェルを使用することができる

In [22]:
!cat my_arraytxt.txt

1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00
4.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00


In [23]:
arr4 = np.loadtxt('my_arraytxt.txt', delimiter=',')

In [24]:
arr4

array([[1., 2., 3.],
       [4., 5., 6.]])