In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
arr1 = np.arange(9).reshape((3,3))

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)
# 列方向に連結

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])

In [7]:
ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [11]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

#行方向への結合なので、元のデータにcat1,追加するデータにcat2をインデックスとして付与

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [12]:
pd.concat([ser1,ser2],keys=['cat1','cat2'],axis=1)

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [13]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])

In [14]:
dframe1

X         Y         Z
0  1.769908 -0.261258  0.852650
1 -1.067609 -1.383157  0.139857
2 -1.427741  0.172613  0.864955
3 -0.141628 -0.463229  0.565264

In [15]:
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [16]:
dframe2

Y         Q         X
0 -1.816216  0.270067  0.288854
1 -2.058772  1.896962  0.136986
2 -0.797428 -0.489758 -0.443722

In [17]:
pd.concat([dframe1,dframe2])

X         Y         Z         Q
0  1.769908 -0.261258  0.852650       NaN
1 -1.067609 -1.383157  0.139857       NaN
2 -1.427741  0.172613  0.864955       NaN
3 -0.141628 -0.463229  0.565264       NaN
0  0.288854 -1.816216       NaN  0.270067
1  0.136986 -2.058772       NaN  1.896962
2 -0.443722 -0.797428       NaN -0.489758

In [18]:
pd.concat([dframe1,dframe2],ignore_index=True)

# indexを連番で保存することができる

X         Y         Z         Q
0  1.769908 -0.261258  0.852650       NaN
1 -1.067609 -1.383157  0.139857       NaN
2 -1.427741  0.172613  0.864955       NaN
3 -0.141628 -0.463229  0.565264       NaN
4  0.288854 -1.816216       NaN  0.270067
5  0.136986 -2.058772       NaN  1.896962
6 -0.443722 -0.797428       NaN -0.489758